### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by fitchettp** [camrossi/cnae#1]
Login failing with following error:
KeyError: 'x-candid-login-otp'

Using CNAE version 3.1(1)

Got it to work by changing the following headers:
X-CANDID-LOGIN-OTP 
X-CANDID-CSRF-TOKEN

to:

X-NAE-LOGIN-OTP
X-NAE-CSRF-TOKEN

**Comment by camrossi** [comment]
I have to admit I haven't used this code in a while. Originally the product was called CANDID and back then the API where in beta.

I guess after the re-branding they updated also the APIs :) 

I will update the code so it will work in the future!
